# Generated by Django 5.0.7 on 2024-08-07 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_restaurantlocation_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlocation',
            name='updatd',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
