# Generated by Django 5.0.7 on 2024-08-13 23:22

import restaurants.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_restaurantlocation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantlocation',
            name='category',
            field=models.CharField(max_length=120, null=True, validators=[restaurants.validators.validate_category]),
        ),
    ]
