# Generated by Django 5.0.7 on 2024-08-18 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Public',
            new_name='public',
        ),
    ]
